site_name: DataRescue Workflow
pages:
- Home: index.md
- Advance Work: advance-work.md
- Seeding: seeding.md
- Researching: researching.md
- Harvesting: harvesting.md
- Checking/Bagging: bagging.md
- Describing: describing.md
- After the Event: after-the-event.md
- Other Useful Documents:
    - Archivers App FAQ: faq.md
    - Archivers App Video Walkthrough: https://www.youtube.com/watch?v=tvSSILnHnpA&feature=youtu.be
    - Crawlable or Uncrawlable: https://drive.google.com/file/d/0B8Gv3Zy5ceY3X0xiSlV2dnhMYWc/view
theme: readthedocs
theme_dir: custom_theme
