site_name: DataRescue Workflow
pages:
    - Home: index.md
    - Advance Work: advance-work.md
    - Seeding: seeding.md
    - Researching: research.md
    - Harvesting: harvesting.md
    - Checking: checking.md
    - Bagging: bagging.md
    - Describing: metadata.md
    - Archivers App FAQ: faq.md
theme: readthedocs
theme_dir: custom_theme
