site_name: DataRescue Workflow
pages:
    - Home: index.md
    - Advance Work: advance-work.md
    - Seeding: seeding.md
    - Researching: researching.md
    - Harvesting: harvesting.md
    - Checking/Bagging: bagging.md
    - Describing: describing.md
    - Archivers App FAQ: faq.md
theme: readthedocs
theme_dir: custom_theme
extra_css:
    - css/extra.css
